# render.yaml - Render Configuration File
services:
  # Main web service
  - type: web
    name: splitfin-zoho-api
    runtime: node
    plan: starter
    buildCommand: npm ci --production=false --prefer-offline --no-audit
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: true
      - key: PUPPETEER_EXECUTABLE_PATH
        value: /usr/bin/google-chrome
      - key: NODE_OPTIONS
        value: "--max-old-space-size=1024"
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: ZOHO_CLIENT_ID
        sync: false
      - key: ZOHO_CLIENT_SECRET
        sync: false
      - key: ZOHO_REFRESH_TOKEN
        sync: false
      - key: ZOHO_ORG_ID
        sync: false
      - key: ZOHO_REDIRECT_URI
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATAFORSEO_LOGIN
        sync: false
      - key: DATAFORSEO_PASSWORD
        sync: false
      - key: CRON_SECRET
        generateValue: true
      
  # High frequency CRON jobs
  - type: cron
    name: high-frequency-sync
    runtime: node
    schedule: "0,15,30,45 9-17 * * 1-5"
    buildCommand: echo "No build needed"
    startCommand: |
      curl -X POST \
      -H "X-Cron-Secret: $CRON_SECRET" \
      https://splitfin-zoho-api.onrender.com/api/cron/high-frequency
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: splitfin-zoho-api
          envVarKey: CRON_SECRET
          
  # Medium frequency CRON jobs
  - type: cron
    name: medium-frequency-sync
    runtime: node
    schedule: "0 */2 * * *"
    buildCommand: echo "No build needed"
    startCommand: |
      curl -X POST \
      -H "X-Cron-Secret: $CRON_SECRET" \
      https://splitfin-zoho-api.onrender.com/api/cron/medium-frequency
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: splitfin-zoho-api
          envVarKey: CRON_SECRET
          
  # Low frequency CRON jobs
  - type: cron
    name: low-frequency-sync
    runtime: node
    schedule: "0 2 * * *"
    buildCommand: echo "No build needed"
    startCommand: |
      curl -X POST \
      -H "X-Cron-Secret: $CRON_SECRET" \
      https://splitfin-zoho-api.onrender.com/api/cron/low-frequency
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: splitfin-zoho-api
          envVarKey: CRON_SECRET
          
  # Weekly deep sync
  - type: cron
    name: weekly-sync
    runtime: node
    schedule: "0 1 * * 0"
    buildCommand: echo "No build needed"
    startCommand: |
      curl -X POST \
      -H "X-Cron-Secret: $CRON_SECRET" \
      https://splitfin-zoho-api.onrender.com/api/cron/low-frequency
    envVars:
      - key: CRON_SECRET
        fromService:
          type: web
          name: splitfin-zoho-api
          envVarKey: CRON_SECRET